name: Terraform enterprise provisioning
on: workflow_dispatch

env:
  WORKSPACE_NAME: "${{ values.workspace_name }}"

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
    - name: "Provisioning Workspace"
      run: echo "WORKSPACE - $WORKSPACE_NAME!"
      